[tool.briefcase]
project_name = "Bee Browse"
bundle = "eu.cafehaine"
version = "0.0.1"
url = "https://github.com/cafehaine/beebrowse"
license = "GNU General Public License v3 (GPLv3)"
author = 'Kilian GUILLAUME'
author_email = "kilian.guillaume@gmail.com"

[tool.briefcase.app.beebrowse]
formal_name = "Bee Browse"
description = "A simple hypertext browser"
icon = "src/beebrowse/resources/beebrowse"
sources = ['src/beebrowse']
requires = []


[tool.briefcase.app.beebrowse.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.beebrowse.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.beebrowse.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.beebrowse.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.beebrowse.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
